---

parser: babel-eslint

extends:
- rackt
- plugin:eslint-plugin-import/warnings
- plugin:eslint-plugin-import/errors

env:
  mocha: true

rules:
  array-bracket-spacing: 0      # [loosen] override rackt
  comma-dangle: 0               # [loosen] override rackt
  object-curly-spacing: 0       # [loosen] override rackt
  no-console: 0                 # [loosen] override upstream (?)
  no-redeclare: 1
  no-unused-vars: [2, {vars: all, args: none}]
  space-infix-ops: 2
